<?php

namespace App\Livewire\Forms;

use App\Enums\Mood;
use App\Models\Entry;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Livewire\Form;

class EntryForm extends Form
{
    public ?Entry $entry = null;
    public $title = null;
    public $slug = '';
    public $content = '';
    public $mood = null;

    public function rules()
    {
        return [
            'title' => 'nullable|min:3|max:255',
            'content' => 'required|min:3',
            'mood' => ['nullable', 'in:' . collect(Mood::cases())->pluck('value')->join(',')],
        ];
    }

    public function setEntry(Entry $entry)
    {
        $this->entry = $entry;

        $this->title = $entry->title;
        $this->slug = $entry->slug;
        $this->content = $entry->content;
        $this->mood = $entry->mood?->value;
    }

    public function updatedTitle(string $value): void
    {
        if (empty($this->title) || $this->slugIsAutoGenerated()) {
            $this->slug = Str::slug($value);
        }
    }

    public function updatedContent(string $value): void
    {
        if (empty($this->title) && empty($this->slug)) {
            $this->slug = Str::slug(
                Str::words(strip_tags($value), 8, '')
            );
        }
    }
    public function save()
    {
        $validated = $this->validate();
        unset($validated['slug']);

        if ($this->entry) {
            $this->entry->update($validated);
        } else {
            $this->entry = Auth::user()
                ->entries()
                ->create($validated);
        }
    }

    private function slugIsAutoGenerated(): bool
    {
        return $this->slug === Str::slug($this->title);
    }
}